### ISSUE TITLE
Tour button invisible in browser due to two scrollbars

### ISSUE THREAD

**Issue by Michadelic** [mauriciolauffer/openui5-tour#1] opened 2018-11-05 12:31 UTC
Hi @mauriciolauffer,

in your UI5Lab sample, the button to start the tour is initially invisible
https://ui5lab.io/browser/#/Samples/openui5.tour/Sample/openui5.tour.openui5-tour.openui5-tourPlayground

Suggestions:
* Fix the height issues to avoid second toolbar  when showing the demo in the browser
* Workround: place button in header with type Emphasized

Thanks,
Michael

**Comment by DusanSacha** [comment] 2018-11-06 13:44
Hi @mauriciolauffer, are you open for contributions?
I like you project and wanted to help out with this issue. (However now I can't reproduce it - the button seems fine. Maybe it was already fixed by you?)

Bests, Dusan

**Comment by Michadelic** [comment] 2018-11-06 16:05
Hi @DusanSacha, i think @mauriciolauffer fixed it with this commit: https://github.com/mauriciolauffer/openui5-tour/commit/f321a98282658c9ec274c7959cb796e160ab0eab

However, there is a small room for improvement, a toolbar should always be in the <subHeader> or <customHeader> aggregation for a sap.m.Page - otherwise it will look odd due to the missing color context:
https://openui5nightly.hana.ondemand.com/#/api/sap.m.Page/aggregations

Its not really a biggie, just pointing it out as i spotted it in the updated sample.
I think @mauriciolauffer is open for pulls, so if you would like to create a correction please go ahead.

Cheers,
Michael

**Comment by mauriciolauffer** [comment] 2018-11-06 22:30
@DusanSacha 
Yes, sure. Feel free to contribute   =)

@Michadelic 
I deliberately put the toolbar into <content> and set its design/color to "Info", therefore it could contrast with the background and make the button more visible. Thanks for the inputs.

**Comment by mauriciolauffer** [comment] 2018-11-06 22:33
#2

**Closed by mauriciolauffer** 2018-11-06 22:33 UTC
Labels: enhancement

**Comment by Michadelic** [comment] 2018-11-07 05:03
Still you shoul put the toolbar in the right aggregation - otherwise the margins are missing :-)
